team_names = ['AC Milan', 'Ajaccio', 'Alaves', 'Almeria', 'Amiens', 'Angers',
       'Arminia Bielefeld', 'Arsenal', 'Aston Villa', 'Atalanta',
       'Athletic Club', 'Atletico Madrid', 'Augsburg', 'Auxerre',
       'Barcelona', 'Bayer Leverkusen', 'Bayern Munich', 'Benevento',
       'Bochum', 'Bologna', 'Bordeaux', 'Borussia Dortmund',
       'Borussia M.Gladbach', 'Bournemouth', 'Brentford', 'Brescia',
       'Brest', 'Brighton', 'Burnley', 'Cadiz', 'Caen', 'Cagliari',
       'Cardiff', 'Carpi', 'Celta Vigo', 'Cesena', 'Chelsea', 'Chievo',
       'Clermont Foot', 'Cordoba', 'Cremonese', 'Crotone',
       'Crystal Palace', 'Darmstadt', 'Deportivo La Coruna', 'Dijon',
       'Eibar', 'Eintracht Frankfurt', 'Elche', 'Empoli', 'Espanyol',
       'Everton', 'Evian Thonon Gaillard', 'FC Cologne', 'Fiorentina',
       'Fortuna Duesseldorf', 'Freiburg', 'Frosinone', 'Fulham',
       'GFC Ajaccio', 'Genoa', 'Getafe', 'Girona', 'Granada',
       'Greuther Fuerth', 'Guingamp', 'Hamburger SV', 'Hannover 96',
       'Hertha Berlin', 'Hoffenheim', 'Huddersfield', 'Hull',
       'Ingolstadt', 'Inter', 'Juventus', 'Las Palmas', 'Lazio', 'Lecce',
       'Leeds', 'Leganes', 'Leicester', 'Lens', 'Levante', 'Lille',
       'Liverpool', 'Lorient', 'Lyon', 'Mainz 05', 'Malaga', 'Mallorca',
       'Manchester City', 'Manchester United', 'Marseille', 'Metz',
       'Middlesbrough', 'Monaco', 'Montpellier', 'Monza', 'Nancy',
       'Nantes', 'Napoli', 'Newcastle United', 'Nice', 'Nimes', 'Norwich',
       'Nottingham Forest', 'Nuernberg', 'Osasuna', 'Paderborn',
       'Palermo', 'Paris Saint Germain', 'Parma', 'Parma Calcio 1913',
       'Pescara', 'Queens Park Rangers', 'RasenBallsport Leipzig',
       'Rayo Vallecano', 'Real Betis', 'Real Madrid', 'Real Sociedad',
       'Real Valladolid', 'Reims', 'Rennes', 'Roma', 'SC Bastia',
       'SD Huesca', 'SPAL 2013', 'Saint-Etienne', 'Salernitana',
       'Sampdoria', 'Sassuolo', 'Schalke 04', 'Sevilla',
       'Sheffield United', 'Southampton', 'Spezia', 'Sporting Gijon',
       'Stoke', 'Strasbourg', 'Sunderland', 'Swansea', 'Torino',
       'Tottenham', 'Toulouse', 'Troyes', 'Udinese', 'Union Berlin',
       'Valencia', 'Venezia', 'Verona', 'VfB Stuttgart', 'Villarreal',
       'Watford', 'Werder Bremen', 'West Bromwich Albion', 'West Ham',
       'Wolfsburg', 'Wolverhampton Wanderers']